name: Deploy to Replicate

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
          sudo chmod +x /usr/local/bin/cog

      - name: Push to Replicate
        env:
          REPLICATE_AUTH_TOKEN: ${{ secrets.REPLICATE_AUTH_TOKEN }}
        run: |
          echo "$REPLICATE_AUTH_TOKEN" | cog login --token-stdin
          cog push r8.im/yourusername/your-model-name