name: Deploy to Replicate

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          curl -s https://install.cog.dev/script.sh | bash
          cog login --token $REPLICATE_API_TOKEN
          cog push r8.im/yourusername/your-model-name